Hw02 unpack string
milov52/otus-hw pull request #2
Opened 2024-06-08 16:41 UTC by milov52

2024-06-08 17:30 UTC, vladislavmass requested changes

2024-06-08 17:30 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	for i := range s {
В го нельзя так итерироваться по строкам, если у нас нет гарантии что строка состоит только из символов ASCII. Так как в данном случае s[i] будет адресовать не символ, а первый байт символа, что сработает для однобайтовой кодировки, но создаст проблемы для многобайтовых кодировок. для демонстрации этого предлогаю добавить следующий тест кейс `{input: "ф2", expected: "фф"},`

2024-06-08 19:00 UTC, milov52 commented on hw02_unpack_string/unpack.go
> +	for i := range s {
Исправлено

2024-06-09 05:14 UTC, vladislavmass requested changes

2024-06-09 05:14 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +				sb.WriteString(tmp[:len(tmp)-1])
Это опять таки не будет работать. Так как откусим не последний символ а его последний байт. `{input: "aaa0ф0", expected: "aa"},` вот тест кейс  который это покажет

2024-06-09 06:02 UTC, milov52 commented on hw02_unpack_string/unpack.go
> +				sb.WriteString(tmp[:len(tmp)-1])
Исправлено

2024-06-09 14:30 UTC, vladislavmass requested changes

2024-06-09 14:30 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	if isDigit(runeArr[0]) || (runeArr[len(runeArr)-1] == '\\' && runeArr[len(runeArr)-2] != '\\') {
Это не будет так работать. Тут нужно поменять подход. Этот фикс не пройдет тест вот такого вида `qwe\\\`. Этот тест кейс должен привести к ошибке, но не приведет.

2024-06-10 04:38 UTC, vladislavmass approved these changes

2024-06-10 07:14 UTC, merged